#include "StartupConfigLog.h"

#include "Config.h"
#include "Logger.h"

namespace somavr {

void LogStartupConfig(const Config& config)
{
    Logger::Instance().Write(
        LogLevel::Info,
        "hook_config_diagnostics comfortPreset=%s frameSummaryInterval=%d matrixSampleLimitPerFrame=%d uniformNameLogLimit=%d uniformMatrixLogLimit=%d uniformMatrixProjectionOnly=%d matrixCapture=%d matrixCaptureFrames=%d matrixCaptureStackDepth=%d matrixCaptureMaxSites=%d matrixCaptureSamplesPerUniform=%d renderDiagnosticCapture=%d renderDiagnosticFrames=%d renderDiagnosticMaxPrograms=%d renderDiagnosticMaxDraws=%d",
        config.comfortPreset.c_str(),
        config.frameSummaryInterval,
        config.matrixSampleLimitPerFrame,
        config.uniformNameLogLimit,
        config.uniformMatrixLogLimit,
        config.uniformMatrixProjectionOnly ? 1 : 0,
        config.matrixCaptureEnabled ? 1 : 0,
        config.matrixCaptureFrames,
        config.matrixCaptureStackDepth,
        config.matrixCaptureMaxSites,
        config.matrixCaptureSamplesPerUniform,
        config.renderDiagnosticCapture ? 1 : 0,
        config.renderDiagnosticFrames,
        config.renderDiagnosticMaxPrograms,
        config.renderDiagnosticMaxDraws);
    Logger::Instance().Write(
        LogLevel::Info,
        "hook_config_camera bridge=%d lifecycleShutdown=%d projectionCenterControl=%d projectionCenteredDefault=%d roomscaleControl=%d roomscaleDefault=%d roomscaleVertical=%d roomscaleSafety=%d safetyClearanceMeters=%.3f safetyRadiusMeters=%.3f safetyVerticalRadiusMeters=%.3f safetyRadialSamples=%d safetyIterations=%d bodyReconciliation=%d bodyThresholdMeters=%.3f bodyTargetMeters=%.3f bodyMaxStepMeters=%.3f bodyHoldFrames=%d eyeHeightOffsetMeters=%.4f reflectionFadeControl=%d nativeRollSuppression=%d logInterval=%d",
        config.hplCameraBridge ? 1 : 0,
        config.hplLifecycleShutdown ? 1 : 0,
        config.hplProjectionCenterControl ? 1 : 0,
        config.hplProjectionCenteredDefault ? 1 : 0,
        config.hplRoomscaleControl ? 1 : 0,
        config.hplRoomscaleEnabledDefault ? 1 : 0,
        config.hplRoomscaleVertical ? 1 : 0,
        config.hplRoomscaleSafety ? 1 : 0,
        config.hplRoomscaleSafetyClearanceMeters,
        config.hplRoomscaleSafetyRadiusMeters,
        config.hplRoomscaleSafetyVerticalRadiusMeters,
        config.hplRoomscaleSafetyRadialSamples,
        config.hplRoomscaleSafetyIterations,
        config.hplRoomscaleBodyReconciliation ? 1 : 0,
        config.hplRoomscaleBodyReconciliationThresholdMeters,
        config.hplRoomscaleBodyReconciliationTargetMeters,
        config.hplRoomscaleBodyReconciliationMaxStepMeters,
        config.hplRoomscaleBodyReconciliationHoldFrames,
        config.hplEyeHeightOffsetMeters,
        config.hplReflectionFadeControl ? 1 : 0,
        config.hplNativeCameraRollSuppression ? 1 : 0,
        config.hplCameraLogInterval);
    Logger::Instance().Write(
        LogLevel::Info,
        "hook_config_render stereoAfr=%d worldScale=%.4f renderStageProbe=%d dualRenderReplayProbe=%d dualRenderAutoProbe=%d dualRenderAutoCount=%d dualRenderAutoDelay=%d dualRenderAutoInterval=%d dualRenderContinuousControl=%d dualRenderContinuousDefault=%d perEyeViewHistoryControl=%d perEyeImageTrailControl=%d toneMappingFrameControl=%d perEyeSSAOTemporalControl=%d ssaoFrameOwnerControl=%d perEyePerformanceTelemetry=%d audioListenerProbe=%d audioListenerCorrection=%d postEffectControl=%d postEffectResourceProbe=%d postEffectBypassDefault=%d disableImageTrail=%d disableChromaticAberration=%d disableRadialBlur=%d shadowJitterControl=%d shadowJitterSuppressedDefault=%d compatibilityLogInterval=%d",
        config.hplStereoAfr ? 1 : 0,
        config.hplWorldScale,
        config.hplRenderStageProbe ? 1 : 0,
        config.hplDualRenderReplayProbe ? 1 : 0,
        config.hplDualRenderAutoProbe ? 1 : 0,
        config.hplDualRenderAutoProbeCount,
        config.hplDualRenderAutoProbeDelayFrames,
        config.hplDualRenderAutoProbeIntervalFrames,
        config.hplDualRenderContinuousControl ? 1 : 0,
        config.hplDualRenderContinuousDefault ? 1 : 0,
        config.hplPerEyeViewHistoryControl ? 1 : 0,
        config.hplPerEyeImageTrailControl ? 1 : 0,
        config.hplToneMappingFrameControl ? 1 : 0,
        config.hplPerEyeSSAOTemporalControl ? 1 : 0,
        config.hplSSAOFrameOwnerControl ? 1 : 0,
        config.hplPerEyePerformanceTelemetry ? 1 : 0,
        config.hplAudioListenerProbe ? 1 : 0,
        config.hplAudioListenerCorrection ? 1 : 0,
        config.hplPostEffectControl ? 1 : 0,
        config.hplPostEffectResourceProbe ? 1 : 0,
        config.hplPostEffectBypassDefault ? 1 : 0,
        config.hplPostEffectDisableImageTrail ? 1 : 0,
        config.hplPostEffectDisableChromaticAberration ? 1 : 0,
        config.hplPostEffectDisableRadialBlur ? 1 : 0,
        config.hplShadowJitterControl ? 1 : 0,
        config.hplShadowJitterSuppressedDefault ? 1 : 0,
        config.hplCompatibilityLogInterval);
    Logger::Instance().Write(
        LogLevel::Info,
        "hook_config_openxr probe=%d sessionProbe=%d releaseAfterProbe=%d bootstrapFrame=%d holdFrames=%d manualStart=%d frameSubmit=%d mirrorBackbuffer=%d desktopMirrorEye=%s desktopMirrorAspect=%s resolutionScalePercent=%d referenceSpace=%s inputEnabled=%d inputLogInterval=%d recoveryEnabled=%d recoveryDelayFrames=%d trackingHoldFrames=%d trackingRecoveryBlackoutFrames=%d",
        config.openxrProbe ? 1 : 0,
        config.openxrSessionProbe ? 1 : 0,
        config.openxrReleaseAfterProbe ? 1 : 0,
        config.openxrBootstrapFrame,
        config.openxrHoldFrames,
        config.openxrManualStart ? 1 : 0,
        config.openxrFrameSubmit ? 1 : 0,
        config.openxrMirrorBackbuffer ? 1 : 0,
        config.openxrDesktopMirrorEye.c_str(),
        config.openxrDesktopMirrorAspect.c_str(),
        config.openxrResolutionScalePercent,
        config.openxrReferenceSpace.c_str(),
        config.openxrInputEnabled ? 1 : 0,
        config.openxrInputLogInterval,
        config.openxrRecoveryEnabled ? 1 : 0,
        config.openxrRecoveryDelayFrames,
        config.openxrTrackingHoldFrames,
        config.openxrTrackingRecoveryBlackoutFrames);
    Logger::Instance().Write(
        LogLevel::Info,
        "controller_config_locomotion enabled=%d moveDeadzone=%.2f moveRelease=%.2f nativeLocomotion=%d movementReference=%s physicalCrouch=%d crouchEnter=%.3f crouchExit=%.3f turnMode=%s turnDeadzone=%.2f turnRelease=%.2f snapPixels=%d smoothPixelsPerSecond=%.1f nativeTurn=%d snapDegrees=%.1f smoothDegreesPerSecond=%.1f nativeTurnSign=%.1f comfortBlackoutFrames=%d",
        config.hplControllerInput ? 1 : 0,
        config.hplControllerMoveDeadzone,
        config.hplControllerMoveReleaseDeadzone,
        config.hplControllerNativeLocomotion ? 1 : 0,
        config.hplControllerMovementReference.c_str(),
        config.hplControllerPhysicalCrouch ? 1 : 0,
        config.hplControllerPhysicalCrouchEnterMeters,
        config.hplControllerPhysicalCrouchExitMeters,
        config.hplControllerSnapTurn ? "snap" : "smooth",
        config.hplControllerTurnDeadzone,
        config.hplControllerTurnReleaseDeadzone,
        config.hplControllerSnapTurnPixels,
        config.hplControllerSmoothTurnPixelsPerSecond,
        config.hplControllerNativeTurn ? 1 : 0,
        config.hplControllerSnapTurnDegrees,
        config.hplControllerSmoothTurnDegreesPerSecond,
        config.hplControllerNativeTurnSign,
        config.hplControllerComfortBlackoutFrames);
    Logger::Instance().Write(
        LogLevel::Info,
        "controller_config_routing interaction=%d bothHands=%d flashlight=%d inventory=%d menu=%d menuPointer=%d menuPointerFov=%.1f,%.1f menuPointerSmoothing=%.3f recenterChord=%d recenterHoldMs=%d haptics=%d hapticAmplitude=%.2f hapticDurationMs=%d dominantHand=%s swapSticks=%d oneHandFallback=%d suppressAuthoredCamera=%d maxInputAgeFrames=%d logInterval=%d",
        config.hplControllerInteraction ? 1 : 0,
        config.hplControllerInteractionBothHands ? 1 : 0,
        config.hplControllerFlashlight ? 1 : 0,
        config.hplControllerInventory ? 1 : 0,
        config.hplControllerMenu ? 1 : 0,
        config.hplControllerMenuPointer ? 1 : 0,
        config.hplControllerMenuPointerHorizontalDegrees,
        config.hplControllerMenuPointerVerticalDegrees,
        config.hplControllerMenuPointerSmoothing,
        config.hplControllerRecenterChord ? 1 : 0,
        config.hplControllerRecenterHoldMs,
        config.hplControllerHaptics ? 1 : 0,
        config.hplControllerHapticAmplitude,
        config.hplControllerHapticDurationMs,
        config.hplControllerDominantHand.c_str(),
        config.hplControllerSwapSticks ? 1 : 0,
        config.hplControllerOneHandFallback ? 1 : 0,
        config.hplControllerSuppressDuringAuthoredCamera ? 1 : 0,
        config.hplControllerMaxInputAgeFrames,
        config.hplControllerLogInterval);
    Logger::Instance().Write(
        LogLevel::Info,
        "controller_config_interaction ray=%d rayOriginTolerance=%.3f grabTranslation=%d translationScale=%.3f maxOffsetMeters=%.3f grabRotation=%d rotationGain=%.2f rotationSign=%.1f maxAngularSpeed=%.2f twoHandHudObject=%d twoHandGrabRotation=%d twoHandSqueeze=%.3f twoHandSeparationMeters=%.3f,%.3f twoHandBlend=%.3f throwRedirect=%d throwVelocityScale=%d throwThreshold=%.3f throwReference=%.3f manipulationMappings=%d",
        config.hplControllerInteractionRay ? 1 : 0,
        config.hplControllerInteractionRayOriginTolerance,
        config.hplControllerGrabTranslation ? 1 : 0,
        config.hplControllerGrabTranslationScale,
        config.hplControllerGrabMaxOffsetMeters,
        config.hplControllerGrabRotation ? 1 : 0,
        config.hplControllerGrabRotationGain,
        config.hplControllerGrabRotationSign,
        config.hplControllerGrabMaxAngularSpeed,
        config.hplControllerTwoHandHudObject ? 1 : 0,
        config.hplControllerTwoHandGrabRotation ? 1 : 0,
        config.hplControllerTwoHandSqueezeThreshold,
        config.hplControllerTwoHandMinSeparationMeters,
        config.hplControllerTwoHandMaxSeparationMeters,
        config.hplControllerTwoHandDirectionBlend,
        config.hplControllerThrowRedirect ? 1 : 0,
        config.hplControllerThrowVelocityScale ? 1 : 0,
        config.hplControllerThrowVelocityThreshold,
        config.hplControllerThrowVelocityReference,
        config.hplControllerManipulationMappings ? 1 : 0);
    Logger::Instance().Write(
        LogLevel::Info,
        "controller_config_hands trackingProbe=%d controllerRoot=%d wristRotation=%d freezePose=%d shoulderVerticalOffsetMeters=%.3f shoulderBackOffsetMeters=%.3f elbowDownMeters=%.3f ergonomics=%d shoulderReach=%d shoulderReachStart=%.3f shoulderReachMaxMeters=%.3f maxSwivelDegreesPerFrame=%.2f rootOffset=%.4f,%.4f,%.4f rootRotationDegrees=%.2f,%.2f,%.2f",
        config.hplHandTrackingProbe ? 1 : 0,
        config.hplHandControllerRoot ? 1 : 0,
        config.hplHandWristRotation ? 1 : 0,
        config.hplHandFreezePose ? 1 : 0,
        config.hplHandShoulderVerticalOffsetMeters,
        config.hplHandShoulderBackOffsetMeters,
        config.hplHandArmIKElbowDownMeters,
        config.hplHandArmIKErgonomics ? 1 : 0,
        config.hplHandShoulderReachCompensation ? 1 : 0,
        config.hplHandShoulderReachStart,
        config.hplHandShoulderReachMaxMeters,
        config.hplHandArmIKMaxSwivelDegreesPerFrame,
        config.hplHandRootOffsetX,
        config.hplHandRootOffsetY,
        config.hplHandRootOffsetZ,
        config.hplHandRootPitchDegrees,
        config.hplHandRootYawDegrees,
        config.hplHandRootRollDegrees);
    Logger::Instance().Write(
        LogLevel::Info,
        "controller_config_presentation hudObject=%d hudOffset=%.4f,%.4f,%.4f hudRotationDegrees=%.2f,%.2f,%.2f flashlightAim=%d flashlightOffset=%.4f,%.4f,%.4f flashlightRotationDegrees=%.2f,%.2f,%.2f",
        config.hplControllerHudObject ? 1 : 0,
        config.hplHudObjectOffsetX,
        config.hplHudObjectOffsetY,
        config.hplHudObjectOffsetZ,
        config.hplHudObjectPitchDegrees,
        config.hplHudObjectYawDegrees,
        config.hplHudObjectRollDegrees,
        config.hplControllerFlashlightAim ? 1 : 0,
        config.hplFlashlightOffsetX,
        config.hplFlashlightOffsetY,
        config.hplFlashlightOffsetZ,
        config.hplFlashlightPitchDegrees,
        config.hplFlashlightYawDegrees,
        config.hplFlashlightRollDegrees);
}

} // namespace somavr
