#pragma once

#include "Logger.h"

#include <filesystem>
#include <string>

namespace somavr {

struct Config {
    LogLevel logLevel = LogLevel::Info;
    std::string comfortPreset = "custom";

    bool hookSwapBuffers = true;
    bool hookWglMakeCurrent = true;
    bool hookFixedFunctionMatrices = true;
    bool hookUniformMatrices = true;
    bool hookViewport = true;
    bool hookDrawCalls = true;
    bool hookFramebuffer = true;

    bool openxrProbe = false;
    bool openxrSessionProbe = false;
    bool openxrReleaseAfterProbe = true;
    int openxrBootstrapFrame = 0;
    int openxrHoldFrames = 0;
    bool openxrManualStart = false;
    bool openxrFrameSubmit = false;
    bool openxrMirrorBackbuffer = true;
    std::string openxrDesktopMirrorEye = "native";
    std::string openxrDesktopMirrorAspect = "fit";
    bool openxrDepthCompositionProbe = false;
    bool openxrDepthCompositionSubmit = false;
    int openxrResolutionScalePercent = 100;
    std::string openxrReferenceSpace = "local";
    bool openxrInputEnabled = false;
    int openxrInputLogInterval = 120;
    bool openxrRecoveryEnabled = true;
    int openxrRecoveryDelayFrames = 120;
    int openxrTrackingHoldFrames = 30;
    int openxrTrackingRecoveryBlackoutFrames = 2;
    bool openxrHudLayer = false;
    int openxrHudWidthPixels = 1600;
    int openxrHudHeightPixels = 900;
    float openxrHudDistanceMeters = 1.5f;
    float openxrHudWidthMeters = 1.6f;
    float openxrHudVerticalOffsetMeters = 0.0f;
    int openxrHudMaxAgeFrames = 2;
    bool openxrHudSuppressCenterCrosshair = false;
    int openxrHudCrosshairClearRadiusPixels = 48;
    bool openxrHudCapturePausedMenu = false;
    bool openxrInteractionReticle = false;
    bool openxrInteractionReticleSemantic = false;
    bool openxrInteractionReticleNativeIcons = false;
    int openxrInteractionReticleSizePixels = 64;
    float openxrInteractionReticleAngularSizeDegrees = 0.75f;
    float openxrInteractionReticleMinSizeMeters = 0.008f;
    float openxrInteractionReticleMaxSizeMeters = 0.08f;
    float openxrInteractionReticleMinDistanceMeters = 0.15f;
    float openxrInteractionReticleMaxDistanceMeters = 8.0f;
    int openxrInteractionReticleMaxAgeFrames = 2;
    bool openxrStatusPanel = false;
    int openxrStatusPanelWidthPixels = 1024;
    int openxrStatusPanelHeightPixels = 512;
    float openxrStatusPanelDistanceMeters = 1.25f;
    float openxrStatusPanelWidthMeters = 1.15f;
    float openxrStatusPanelVerticalOffsetMeters = 0.0f;
    bool hplControllerInput = false;
    float hplControllerMoveDeadzone = 0.35f;
    float hplControllerMoveReleaseDeadzone = 0.25f;
    bool hplControllerNativeLocomotion = true;
    std::string hplControllerMovementReference = "body";
    bool hplControllerPhysicalCrouch = false;
    float hplControllerPhysicalCrouchEnterMeters = 0.35f;
    float hplControllerPhysicalCrouchExitMeters = 0.25f;
    bool hplControllerSnapTurn = true;
    float hplControllerTurnDeadzone = 0.65f;
    float hplControllerTurnReleaseDeadzone = 0.35f;
    int hplControllerSnapTurnPixels = 420;
    float hplControllerSmoothTurnPixelsPerSecond = 900.0f;
    bool hplControllerNativeTurn = true;
    float hplControllerSnapTurnDegrees = 30.0f;
    float hplControllerSmoothTurnDegreesPerSecond = 120.0f;
    float hplControllerNativeTurnSign = -1.0f;
    bool hplControllerInteraction = true;
    bool hplControllerFlashlight = true;
    bool hplControllerInventory = true;
    bool hplControllerMenu = true;
    bool hplControllerMenuPointer = true;
    float hplControllerMenuPointerHorizontalDegrees = 70.0f;
    float hplControllerMenuPointerVerticalDegrees = 50.0f;
    float hplControllerMenuPointerSmoothing = 0.35f;
    bool hplControllerTerminalPointer = true;
    float hplControllerTerminalPointerHorizontalDegrees = 70.0f;
    float hplControllerTerminalPointerVerticalDegrees = 50.0f;
    float hplControllerTerminalPointerSmoothing = 0.35f;
    bool hplControllerRecenterChord = true;
    bool hplControllerHaptics = true;
    float hplControllerHapticAmplitude = 0.35f;
    int hplControllerHapticDurationMs = 30;
    bool hplControllerGameplayHaptics = true;
    float hplControllerGameplayHapticAmplitudeScale = 0.75f;
    float hplControllerGameplayHapticMinAmplitude = 0.05f;
    float hplControllerGameplayHapticRetriggerDelta = 0.08f;
    int hplControllerGameplayHapticRefreshMs = 80;
    int hplControllerGameplayHapticSegmentMs = 100;
    bool hplControllerFocusHaptics = false;
    float hplControllerFocusHapticAmplitude = 0.12f;
    int hplControllerFocusHapticDurationMs = 15;
    int hplControllerFocusHapticCooldownFrames = 15;
    std::string hplControllerDominantHand = "right";
    bool hplControllerSwapSticks = false;
    bool hplControllerOneHandFallback = true;
    bool hplControllerSuppressDuringAuthoredCamera = true;
    bool hplControllerInteractionRay = false;
    float hplControllerInteractionRayOriginTolerance = 0.75f;
    bool hplControllerGrabTranslation = false;
    float hplControllerGrabTranslationScale = 1.0f;
    float hplControllerGrabMaxOffsetMeters = 0.75f;
    bool hplControllerGrabRotation = false;
    float hplControllerGrabRotationGain = 100.0f;
    float hplControllerGrabRotationSign = 1.0f;
    float hplControllerGrabMaxAngularSpeed = 6.0f;
    bool hplControllerTwoHandHudObject = false;
    bool hplControllerTwoHandGrabRotation = false;
    float hplControllerTwoHandSqueezeThreshold = 0.75f;
    float hplControllerTwoHandMinSeparationMeters = 0.08f;
    float hplControllerTwoHandMaxSeparationMeters = 1.2f;
    float hplControllerTwoHandDirectionBlend = 1.0f;
    bool hplControllerThrowRedirect = false;
    bool hplControllerThrowVelocityScale = false;
    float hplControllerThrowVelocityThreshold = 0.35f;
    float hplControllerThrowVelocityReference = 2.0f;
    bool hplControllerManipulationMappings = true;
    bool hplControllerManipulationMotion = false;
    float hplControllerManipulationMotionPixelsPerMeter = 900.0f;
    float hplControllerManipulationMotionDeadzoneMeters = 0.0005f;
    int hplControllerManipulationMotionMaxPixelsPerFrame = 80;
    float hplControllerManipulationMotionHorizontalSign = 1.0f;
    float hplControllerManipulationMotionVerticalSign = -1.0f;
    bool hplHandTrackingProbe = false;
    bool hplHandControllerRoot = false;
    float hplHandRootOffsetX = 0.0f;
    float hplHandRootOffsetY = -0.075f;
    float hplHandRootOffsetZ = 0.0f;
    float hplHandRootPitchDegrees = 0.0f;
    float hplHandRootYawDegrees = 0.0f;
    float hplHandRootRollDegrees = 0.0f;
    bool hplControllerHudObject = false;
    float hplHudObjectOffsetX = 0.0f;
    float hplHudObjectOffsetY = 0.0f;
    float hplHudObjectOffsetZ = 0.0f;
    float hplHudObjectPitchDegrees = 0.0f;
    float hplHudObjectYawDegrees = 0.0f;
    float hplHudObjectRollDegrees = 0.0f;
    bool hplControllerFlashlightAim = false;
    bool hplControllerFlashlightGameplayRay = false;
    float hplFlashlightOffsetX = 0.0f;
    float hplFlashlightOffsetY = 0.0f;
    float hplFlashlightOffsetZ = 0.03f;
    float hplFlashlightPitchDegrees = 0.0f;
    float hplFlashlightYawDegrees = 0.0f;
    float hplFlashlightRollDegrees = 0.0f;
    int hplControllerComfortBlackoutFrames = 2;
    int hplControllerStateTransitionBlackoutFrames = 0;
    int hplControllerRecenterHoldMs = 900;
    int hplControllerMaxInputAgeFrames = 8;
    int hplControllerLogInterval = 120;
    bool forceDisableVsync = false;

    int frameSummaryInterval = 120;
    int matrixSampleLimitPerFrame = 32;
    int uniformNameLogLimit = 256;
    int uniformMatrixLogLimit = 256;
    bool uniformMatrixProjectionOnly = true;
    bool matrixCaptureEnabled = false;
    int matrixCaptureFrames = 120;
    int matrixCaptureStackDepth = 8;
    int matrixCaptureMaxSites = 64;
    int matrixCaptureSamplesPerUniform = 4;
    bool renderDiagnosticCapture = false;
    int renderDiagnosticFrames = 4;
    int renderDiagnosticMaxPrograms = 128;
    int renderDiagnosticMaxDraws = 8192;
    bool hplCameraBridge = false;
    bool hplLifecycleShutdown = false;
    bool hplProjectionCenterControl = false;
    bool hplProjectionCenteredDefault = false;
    bool hplRoomscaleControl = false;
    bool hplRoomscaleEnabledDefault = true;
    bool hplRoomscaleVertical = true;
    bool hplRoomscaleSafety = false;
    bool hplRoomscaleSafetyDynamic = false;
    float hplRoomscaleSafetyClearanceMeters = 0.02f;
    int hplRoomscaleSafetyIterations = 6;
    float hplRoomscaleSafetyRadiusMeters = 0.09f;
    float hplRoomscaleSafetyVerticalRadiusMeters = 0.12f;
    int hplRoomscaleSafetyRadialSamples = 6;
    bool hplRoomscaleBodyReconciliation = false;
    float hplRoomscaleBodyReconciliationThresholdMeters = 0.45f;
    float hplRoomscaleBodyReconciliationTargetMeters = 0.25f;
    float hplRoomscaleBodyReconciliationMaxStepMeters = 0.015f;
    int hplRoomscaleBodyReconciliationHoldFrames = 30;
    float hplEyeHeightOffsetMeters = 0.0f;
    bool hplRecenterControl = false;
    bool hplReflectionFadeControl = false;
    bool hplNativeCameraRollSuppression = false;
    bool hplComfortCameraAddControl = false;
    bool hplComfortSuppressHeadBob = true;
    bool hplComfortSuppressCameraShake = true;
    bool hplComfortSuppressSway = false;
    bool hplComfortCameraRollControl = false;
    bool hplComfortSuppressScriptRoll = false;
    bool hplComfortSuppressLeanRoll = true;
    bool hplComfortSuppressMoveRoll = true;
    bool hplComfortSuppressClimbRoll = true;
    bool hplComfortDepthOfFieldControl = false;
    bool hplComfortOpticsControl = false;
    bool hplComfortSuppressFov = true;
    bool hplComfortSuppressFovMultiplier = true;
    bool hplComfortSuppressAspectMultiplier = true;
    bool hplLoadingScreenControl = false;
    int hplLoadingScreenExitBlackoutFrames = 2;
    bool hplScriptedPresentationControl = false;
    bool hplInventoryPresentationControl = false;
    bool hplVideoLifecycleProbe = false;
    bool hplScreenEffectControl = false;
    float hplScreenEffectDistanceMeters = 1.5f;
    bool hplSubtitleControl = false;
    float hplSubtitleWidthScale = 0.9f;
    float hplSubtitleFontScale = 1.15f;
    float hplSubtitleVerticalOffset = 0.0f;
    int hplComfortLogInterval = 120;
    int hplCameraLogInterval = 120;
    bool hplStereoAfr = false;
    float hplWorldScale = 1.0f;
    bool hplRenderStageProbe = false;
    bool hplDualRenderReplayProbe = false;
    bool hplDualRenderAutoProbe = false;
    int hplDualRenderAutoProbeCount = 3;
    int hplDualRenderAutoProbeDelayFrames = 180;
    int hplDualRenderAutoProbeIntervalFrames = 180;
    bool hplDualRenderContinuousControl = false;
    bool hplDualRenderContinuousDefault = false;
    bool hplPerEyeViewHistoryControl = false;
    bool hplPerEyePerformanceTelemetry = false;
    bool hplPerEyeGpuTelemetry = false;
    int hplGpuQueryPoolSize = 128;
    bool hplAudioListenerProbe = false;
    bool hplAudioListenerCorrection = false;
    bool hplAudioListenerTranslation = false;
    bool hplPostEffectControl = false;
    bool hplPostEffectResourceProbe = false;
    bool hplPostEffectBypassDefault = false;
    bool hplPostEffectDisableImageTrail = true;
    bool hplPostEffectDisableVideoDistortion = true;
    bool hplPostEffectDisableChromaticAberration = true;
    bool hplPostEffectDisableRadialBlur = true;
    bool hplShadowJitterControl = false;
    bool hplShadowJitterSuppressedDefault = false;
    int hplCompatibilityLogInterval = 120;
};

class ConfigManager {
public:
    bool Initialize();
    bool InitializeAtPath(const std::filesystem::path& path);

    const Config& Get() const;
    const std::filesystem::path& Path() const;

private:
    void WriteDefaultConfig() const;
    void LoadFromFile();

    Config config_;
    std::filesystem::path path_;
};

} // namespace somavr
